- dataset_id: "amaai-lab/MusicBench"
  local_dir: "data/amaai-lab-MusicBench"
  platform: "HuggingFace"

- dataset_id: "CLAPv2/MusicCaps"
  local_dir: "data/CLAPv2-MusicCaps"
  platform: "HuggingFace"
