- preset_name:  "MusicGen-Small-MusicCaps-finetuning"
  model_id: "facebook/musicgen-small"
  dataset: "CLAPv2/MusicCaps"
  output_model_dir: "ckpts/MusicGen-Small-MusicCaps-finetuning"
  third_party: "https://github.com/danhtran2mind/musicgen-dreamboothing.git"

- preset_name: "AudioLDM-finetuning"
  model_id: "ayousanz/AudioLDM-training-finetuning"
  dataset: "amaai-lab/MusicBench"
  output_model_dir: "ckpts/AudioLDM-finetuning/log"
  third_party: "https://github.com/danhtran2mind/Text2Audio-AudioLDM.git"
